TOP_DIR = ..
COMMON_DIR = ${TOP_DIR}/common

BASE = ram

SRC = ./tb_ram.sv ./ram.sv \
	  ${COMMON_DIR}/clk_rst.sv ${COMMON_DIR}/dff.sv ${COMMON_DIR}/tilelink.sv \
	  ${COMMON_DIR}/load.c

include ${TOP_DIR}/makefile.common
