TOP_DIR = ..
COMMON_DIR = ${TOP_DIR}/common

BASE = rom

SRC = ./tb_rom.sv ./stimulator.sv ./rom_backend.sv \
	  ./rom_front.sv ./rom_wr.sv ./rom_rd.sv \
	  ${COMMON_DIR}/clk_rst.sv ${COMMON_DIR}/dff.sv ${COMMON_DIR}/tilelink.sv

include ${TOP_DIR}/makefile.common
