TOP_DIR = ../..
COMMON_DIR = ${TOP_DIR}/common

BASE = uart

SRC = ./tb_uart.sv ../stimulator.sv ./uart_stub.sv ./uart.c \
	  ${COMMON_DIR}/clk_rst.sv ${COMMON_DIR}/dff.sv ${COMMON_DIR}/tilelink.sv

include ${TOP_DIR}/makefile.common
