TOP_DIR = ..
COMMON_DIR = ${TOP_DIR}/common

BASE = access

SRC = ./tb_access.sv ./stimulator.sv ./access.sv ./stage_ma_wb.sv \
	  ../ram/ram.sv \
	  ${COMMON_DIR}/dff.sv ${COMMON_DIR}/clk_rst.sv \
	  ${COMMON_DIR}/io_ops.sv ${COMMON_DIR}/tilelink.sv

include ${TOP_DIR}/makefile.common
