TOP_DIR = ..
COMMON_DIR = ${TOP_DIR}/common

BASE = execute

SRC = ./tb_execute.sv ./stimulator.sv ./execute.sv ./stage_ex_ma.sv \
	  ./alu.sv ./jmp_br.sv ./system_ctl.sv ./dbg_execute.sv \
	  ${COMMON_DIR}/dff.sv ${COMMON_DIR}/clk_rst.sv \
	  ${COMMON_DIR}/alu_ops.sv ${COMMON_DIR}/io_ops.sv \
	  ${COMMON_DIR}/bj_ops.sv ${COMMON_DIR}/sys_ops.sv ${COMMON_DIR}/forward.sv

include ${TOP_DIR}/makefile.common
